	" Themes
	source $HOME/.config/nvim/vim_script/themes/edge.vim
	source $HOME/.config/nvim/vim_script/themes/onedark.vim
	source $HOME/.config/nvim/vim_script/themes/sonokai.vim
	source $HOME/.config/nvim/vim_script/themes/everforest.vim
	source $HOME/.config/nvim/vim_script/themes/miramare.vim
	source $HOME/.config/nvim/vim_script/themes/oceanic-next.vim
	source $HOME/.config/nvim/vim_script/themes/oceanic-material.vim
	source $HOME/.config/nvim/vim_script/themes/emberk.vim
	" Plugins
	source $HOME/.config/nvim/vim_script/plugins/plugins_config.vim
	source $HOME/.config/nvim/vim_script/plugins/coc-config.vim
	source $HOME/.config/nvim/vim_script/plugins/coc-extensions.vim
	source $HOME/.config/nvim/vim_script/plugins/vim-javascript.vim
	source $HOME/.config/nvim/vim_script/plugins/vim-typescript.vim
	source $HOME/.config/nvim/vim_script/plugins/vim-prettier.vim
	source $HOME/.config/nvim/vim_script/plugins/vim-closetag.vim
	source $HOME/.config/nvim/vim_script/plugins/nvim-dashboard.vim
	source $HOME/.config/nvim/vim_script/plugins/tree-lua.vim
	" Key Maps
	source $HOME/.config/nvim/nmaps/nmaps.vim
