	" THEMES:
	source ~/AppData/Local/nvim/vim_script/themes/edge.vim
	source ~/AppData/Local/nvim/vim_script/themes/onedark.vim
	source ~/AppData/Local/nvim/vim_script/themes/sonokai.vim
	source ~/AppData/Local/nvim/vim_script/themes/everforest.vim
	source ~/AppData/Local/nvim/vim_script/themes/miramare.vim
	source ~/AppData/Local/nvim/vim_script/themes/oceanic-next.vim
	source ~/AppData/Local/nvim/vim_script/themes/oceanic-material.vim
	source ~/AppData/Local/nvim/vim_script/themes/emberk.vim
	" PLUGINS:
	source ~/AppData/Local/nvim/vim_script/plugins/plugins_config.vim
	source ~/AppData/Local/nvim/vim_script/plugins/vim-closetag.vim
	source ~/AppData/Local/nvim/vim_script/plugins/nvim-dashboard.vim
	" KEY_MAPS:
	source ~/AppData/Local/nvim/nmaps/nmaps.vim
